### ISSUE TITLE
AT commands for wifi-subsys

### ISSUE THREAD

**Issue by xkevin190** [Mesh4all/m4a-firmware#117]
#### Description

AT commands will used for  handle the wifi for example turn on a AP or sta mode the AT command that i propose are:
| Starts | Type | Command | Value | Ends | Description |
|---------|---------|---------------|---------|---------|-----------------|
| `AT`   | `+` | `WAP_SSID` | AP_SSID  | `\r\n` | Set the  AP SSID |
| `AT`   | `+` | `WAP_PASS` | AP Password | `\r\n` | Set the  AP password |
| `AT`   | `+` | `WSTA_SSID` | STA SSID | `\r\n` | Set the STA SSID |
| `AT `  | `+` | `WSTA_PASS` |STA PAssword  | `\r\n` |  Set the STA password |
| `AT`   | `+` | `WIFI_OFF` | None | `\r\n` | Turn off the WiFi interface |
| `AT `  | `+` | `WIFI_ON` | None  | `\r\n` |Turn on the WiFi interface |
| `AT `  | `+` | `NVS_RST` | None |`\r\n` | Restore the subsystem to factory settings |
| `AT `  | `+` | `WIFI_MODE` | 0 / 1 / 2 / 3 | `\r\n` | Sets  the WiFi mode to None / AP / STA / AP+STA |
| `AT `  | `+` | `WAP_CHAN` | Number | `\r\n` | Sets the  AP channel |
| `AT `  | `+` | `WAP_AUTH` | Number as AUTH_TYPE |  `\r\n` |  Sets the authentication type |
| `AT `  | `+` | `WIFI_RST` | None | `\r\n` |  Restart |

This commands are the first propose please check it and share with us your opinions.

**Comment by luisan00** [comment]
Updated description  @xkevin190  :+1:
