### ISSUE TITLE
docs: Add Contributors File [@luisan00. @feedurhead @Feedurhead-1 @jacoboamn87 @rosana4]

### ISSUE THREAD

**Issue by eduazocar** [Mesh4all/m4a-firmware#27]
#### Description

I need to start adding contributors file, please everyone , could you please send me your info, github username, email, name, any content to be used as an identifier [@luisan00. @Feedurhead @Feedurhead-1 @jacoboamn87 @rosana4]

**Comment by luisan00** [comment]
> ... github username, email, name, any content to be used as an identifier

If name, user and  email then :

| Name | Github User | email |
|:---|:---|:---|
| Luis A. Ruiz | @luisan00 | luisan00@hotmail.com |

if it's two fields then take my name and email @eduazocar

**Comment by eduazocar** [comment]
Thanks @luisan00

**Comment by luisan00** [comment]
Please remove fossa... It's only a bot,, but add @Feedurhead-1

**Comment by luisan00** [comment]
@eduazocar  this should be driven by writing in the PR description(as described in the PR template) Fix #[issue number], for automatic resolution. if not, you need to close by hand after merging
