### ISSUE TITLE
Add ds18 temperature sensor.

### ISSUE THREAD

**Issue by xkevin190** [Mesh4all/m4a-firmware#74]
### Description
Is necessary add the implementation of sensor of temperature ds18 for the firmware, for this is advisable see the riot implenmetation for this device.

### Useful links

Documentation of RIOT for the ds18: 
https://doc.riot-os.org/group__drivers__ds18.html

RIOT test of the driver:
https://github.com/RIOT-OS/RIOT/tree/master/tests/driver_ds18

**Comment by eduazocar** [comment]
This issue was fixed with #65

**Comment by xkevin190** [comment]
@eduazocar this Issue is for the firmware implementation, the PR #66 is an example, is necessary to add how peripheral inside firmware y add his documentation how should be use.
